Algoritmo "ordemDecrescente_51"
// Disciplina   : Lógica de Programação]
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Nathan Vasconcelos Garrett
// Data atual  : 05/09/2023
Var
   // Seção de Declarações das variáveis

   x: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   x <- 11
   
   enquanto x >= 2 faca
      x <- x - 1
      Escreval("Olá os números estão em ordem decrescente: ", x)
   fimenquanto

Fimalgoritmo